version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Hospital990@"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "Hospital990@"]
    networks:
      - backend

volumes:
  sql_data:

networks:
  backend:
    driver: bridge
