<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.5.0" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="9.23.90" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.17" />
    <Content Include="Common/EmailTemplates/*.html" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
